version: '3.8'

services:
  app:
    profiles: ["production"]
    build:
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - "80:3000"
    command: npm start
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
