apiVersion: v1
kind: Secret
metadata:
  name: degenz-lounge-secrets
type: Opaque
stringData:
  database_url: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres-service:5432/degenz_lounge"
  redis_url: "redis://:${REDIS_PASSWORD}@redis-service:6379/0"
  jwt_secret: "${JWT_SECRET}"
  supabase_anon_key: "${SUPABASE_ANON_KEY}"
  supabase_service_key: "${SUPABASE_SERVICE_KEY}"
  stripe_public_key: "${STRIPE_PUBLIC_KEY}"
  stripe_secret_key: "${STRIPE_SECRET_KEY}"
  stripe_webhook_secret: "${STRIPE_WEBHOOK_SECRET}"
  gemini_api_key: "${GEMINI_API_KEY}"
